# ==========================================================================
# /etc/nginx/sites-available/webapp
# NGINX in front of 3 Docker containers (host ports 3001 / 3002 / 3003)
# Roles: web server · reverse proxy · load balancer · cache · gzip
# ==========================================================================

# CACHE MANAGER
proxy_cache_path /var/cache/nginx/webapp # disk storage folder
	levels=1:2 # internal directory structure (performance)
	keys_zone=app_cache:10m # name + 10 MB of RAM for keys
	max_size=500m # disk space limit
	inactive=60m # purge unused entries every 60 minutes
	use_temp_path=off;

# LOAD BALANCER CLUSTERS
upstream webapp_cluster {
	least_conn;
	server localhost:3001;
	server localhost:3002; 
	server localhost:3003;
}

# LOG FORMAT
log_format upstreamlog '$remote_addr -> $upstream_addr '
                       '[$status] "$request" '
                       'cache=$upstream_cache_status';

# REDIRECT HTTP to HTTPS
server {
    listen 8080;
    server_name localhost;
    return 301 https://$host$request_uri;
}

# WEB SERVER + REVERSE PROXY
server { 
	listen 443 ssl;        # port 443 = HTTP
	server_name localhost; # local domain for test 

	# LOG THE ACCESS
	access_log /var/log/nginx/webapp.log upstreamlog;

	# SSL Certificate
        ssl_certificate     /etc/nginx/certs/selfsigned.crt;   # the certificate
        ssl_certificate_key /etc/nginx/certs/selfsigned.key;   # the private key
        ssl_protocols       TLSv1.2 TLSv1.3;                   # modern versions only
        ssl_ciphers         HIGH:!aNULL:!MD5;

	# COMPRESSION (gzip)
	# (gzip on; is already global in nginx.conf; we refine it here) 
	gzip on; 
	gzip_comp_level 5; 
	gzip_min_length 1024; 
	gzip_proxied any; # also compresses proxied responses 
	gzip_vary on; 
	gzip_types text/plain text/css application/json 
	application/javascript image/svg+xml; 
	
	location / { 
		# REVERSE PROXY + LOAD BALANCING
		proxy_pass http://webapp_cluster; 
		# Headers passed to backends to manage all URLs behind / 
		# Backends see only what Nginx forward to them
		proxy_set_header Host $host;  # can see original request
		proxy_set_header X-Real-IP $remote_addr;  # original remote IP
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
		proxy_set_header X-Forwarded-Proto $scheme; 
		
		# to see cache working on images
		proxy_ignore_headers Cache-Control Expires;

		# CACHE
		# disable while testing load balancing
		# proxy_cache off;
		proxy_cache app_cache; 
		proxy_cache_valid 200 302 10m; # answers OK: 10 min 
		proxy_cache_valid 404 1m; # "not found": 1 min 
		# Respects client's "no-cache" setting
		proxy_cache_bypass $http_cache_control;		
		
		# Debug header: HIT / MISS / BYPASS (visible in devtools)
		add_header X-Cache-Status $upstream_cache_status;
	}
}
